//
// Created by dmitry on 05.05.2026.
//

#ifndef SOUNDSSTORAGESERVICE_CUSTOMERWALLETSREPODITORY_H
#define SOUNDSSTORAGESERVICE_CUSTOMERWALLETSREPODITORY_H



class CustomerWalletsRepoditory {

};



#endif //SOUNDSSTORAGESERVICE_CUSTOMERWALLETSREPODITORY_H
