changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/soundwave
username=postgres
password=postgres
driver=org.postgresql.Driver
classpath=/home/dmitry/dikpik/database/tools/liquibase/lib/postgresql-42.7.1.jar
logLevel=info
