//
// Created by dmitry on 05.05.2026.
//

#ifndef SOUNDSSTORAGESERVICE_CUSTOMERWALLETSSERVICE_H
#define SOUNDSSTORAGESERVICE_CUSTOMERWALLETSSERVICE_H



class CustomerWalletsService {

};



#endif //SOUNDSSTORAGESERVICE_CUSTOMERWALLETSSERVICE_H
