server {
    listen 80;
    server_name soundwave.divmone.ru;

    client_max_body_size 100M;

    resolver 127.0.0.11 valid=30s;
    set $auth_service    http://auth-service:8080;
    set $sounds_service  http://sounds-storage:8080;

    root /usr/share/nginx/html;
    index index.html;

    location = /auth/google {
        proxy_pass         $auth_service;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location = /auth/logout {
        proxy_pass         $auth_service;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /api/ {
        proxy_pass         $sounds_service;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $http_x_forwarded_proto;
        client_max_body_size 100M;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name pgadmin.soundwave.divmone.ru;

    location / {
        proxy_pass http://pgadmin:80;  # pgadmin контейнер
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}