/**
 *
 *  CustomerWallets.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "CustomerWallets.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::soundwaveCryptoPayment;

const std::string CustomerWallets::Cols::_user_id = "\"user_id\"";
const std::string CustomerWallets::Cols::_wallet = "\"wallet\"";
const std::vector<std::string> CustomerWallets::primaryKeyName = {"user_id","wallet"};
const bool CustomerWallets::hasPrimaryKey = true;
const std::string CustomerWallets::tableName = "\"customer_wallets\"";

const std::vector<typename CustomerWallets::MetaData> CustomerWallets::metaData_={
{"user_id","int64_t","bigint",8,1,1,1},
{"wallet","std::string","character varying",32,0,1,1}
};
const std::string &CustomerWallets::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
CustomerWallets::CustomerWallets(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["wallet"].isNull())
        {
            wallet_=std::make_shared<std::string>(r["wallet"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            wallet_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

CustomerWallets::CustomerWallets(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            wallet_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

CustomerWallets::CustomerWallets(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("wallet"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["wallet"].isNull())
        {
            wallet_=std::make_shared<std::string>(pJson["wallet"].asString());
        }
    }
}

void CustomerWallets::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            wallet_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void CustomerWallets::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("wallet"))
    {
        if(!pJson["wallet"].isNull())
        {
            wallet_=std::make_shared<std::string>(pJson["wallet"].asString());
        }
    }
}

const int64_t &CustomerWallets::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &CustomerWallets::getUserId() const noexcept
{
    return userId_;
}
void CustomerWallets::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[0] = true;
}

const std::string &CustomerWallets::getValueOfWallet() const noexcept
{
    static const std::string defaultValue = std::string();
    if(wallet_)
        return *wallet_;
    return defaultValue;
}
const std::shared_ptr<std::string> &CustomerWallets::getWallet() const noexcept
{
    return wallet_;
}
void CustomerWallets::setWallet(const std::string &pWallet) noexcept
{
    wallet_ = std::make_shared<std::string>(pWallet);
    dirtyFlag_[1] = true;
}
void CustomerWallets::setWallet(std::string &&pWallet) noexcept
{
    wallet_ = std::make_shared<std::string>(std::move(pWallet));
    dirtyFlag_[1] = true;
}

void CustomerWallets::updateId(const uint64_t id)
{
}
typename CustomerWallets::PrimaryKeyType CustomerWallets::getPrimaryKey() const
{
    return std::make_tuple(*userId_,*wallet_);
}

const std::vector<std::string> &CustomerWallets::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "wallet"
    };
    return inCols;
}

void CustomerWallets::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getWallet())
        {
            binder << getValueOfWallet();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> CustomerWallets::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void CustomerWallets::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getWallet())
        {
            binder << getValueOfWallet();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value CustomerWallets::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getWallet())
    {
        ret["wallet"]=getValueOfWallet();
    }
    else
    {
        ret["wallet"]=Json::Value();
    }
    return ret;
}

std::string CustomerWallets::toString() const
{
    return toJson().toStyledString();
}

Json::Value CustomerWallets::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getWallet())
            {
                ret[pMasqueradingVector[1]]=getValueOfWallet();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getWallet())
    {
        ret["wallet"]=getValueOfWallet();
    }
    else
    {
        ret["wallet"]=Json::Value();
    }
    return ret;
}

bool CustomerWallets::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("wallet"))
    {
        if(!validJsonOfField(1, "wallet", pJson["wallet"], err, true))
            return false;
    }
    else
    {
        err="The wallet column cannot be null";
        return false;
    }
    return true;
}
bool CustomerWallets::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CustomerWallets::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("wallet"))
    {
        if(!validJsonOfField(1, "wallet", pJson["wallet"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool CustomerWallets::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CustomerWallets::validJsonOfField(size_t index,
                                       const std::string &fieldName,
                                       const Json::Value &pJson,
                                       std::string &err,
                                       bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
