changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/soundwaveSounds
username=postgres
password=postgres
driver=org.postgresql.Driver
classpath=/home/dmitry/gdikvpi/SoundWave/backend/soundsStorageService/database/tools/lib/postgresql-42.7.1.jar
logLevel=info
