//
// Created by dmitry on 05.05.2026.
//

#ifndef SOUNDSSTORAGESERVICE_CUSTOMERWALLETSCONTROLLER_H
#define SOUNDSSTORAGESERVICE_CUSTOMERWALLETSCONTROLLER_H



class CustomerWalletsController {

};



#endif //SOUNDSSTORAGESERVICE_CUSTOMERWALLETSCONTROLLER_H
